name: "Create PR"
on: push

jobs:
  create-pr-on-push:
    if: ${{ (contains(github.event.head_commit.message, 'BUG') || contains(github.event.head_commit.message, 'IMP'))  && github.event.pull_request.merged == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Git
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"
      - name: Get branch name
        id: branch_name
        run: echo "::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Get last commit message
        id: last_commit_message
        run: echo "::set-output name=last_commit_message::$(git log -1 --pretty=format:'%s')"
      - name: Create pull request
        uses: thomaseizinger/create-pull-request@master
        with:
          github_token: ${{ secrets.SSH }}
          head: ${{ github.ref }}
          base: main
          title: "[${{ steps.branch_name.outputs.branch_name }}] ${{ steps.last_commit_message.outputs.last_commit_message }}"
