on: push

jobs:
  pull-request:
    if: contains(github.event.head_commit.message, 'done')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Git
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"
      - name: Get branch name
        id: branch_name
        run: echo "::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Get last commit message
        id: last_commit_message
        run: echo "::set-output name=last_commit_message::$(git log -1 --pretty=format:'%s')"
      - name: pull-request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          source_branch: ""
          destination_branch: "main"
          pr_title: "[${{ steps.branch_name.outputs.branch_name }}] ${{ steps.last_commit_message.outputs.last_commit_message }}"
          pr_body: |
            :crown: *An automated PR*
          pr_template: ".github/pull_request_template.md"
          github_token: ${{ secrets.SSH }}
