name: Auto PR Title

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=branch_name::$(echo ${{ github.event.pull_request.head.ref }})"

      - name: Set PR Title
        id: set_pr_title
        run: echo "::set-output name=title::Auto PR::$(echo ${{ steps.extract_branch.outputs.branch_name }})"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: ${{ steps.set_pr_title.outputs.title }}
          branch: ${{ github.event.pull_request.head.ref }}
          base: main
          token: ${{ secrets.GITHUB_TOKEN }}
