name: Auto PR Title

on:
  pull_request:
    types:
      - opened

jobs:
  auto-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Set PR Title
        run: |
          branch_name=$(echo ${{ github.event.pull_request.head.ref }})
          title="Automated PR Title for $branch_name"
          echo "::set-output name=title::${title}"

      - name: Update PR
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.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 }}
          script: |
            const title = process.env.title;
            github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              title: title
            });
